version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2015
configuration: release
platform: x64
environment:
  PATH: C:\Program Files\Project\bin;%PATH%
build_script:
- ps: >-
    powershell ci\appveyor\buildTestCI.ps1
test_script:
- cmd: >-
    ECHO this is batch
    
    ECHO this is batch again
    
    cd testcases
    dir