version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2015
configuration: release
platform: x64
environment:
  PYTHON: C:/Python37-x64
  PATH: C:/Program Files/Project\bin;C:/Program Files/Project;%PATH%
build_script:
- ps: >-
    powershell ci\appveyor\buildTestCI.ps1
test_script:
- cmd: >-
    ECHO this is batch
    
    ECHO this is batch again
    
    cd testcases
    
    ECHO %PATH%
    
    %PYTHON%/python.exe regressionTests.py --mpirunPath=mpiexec.exe --exePath=Test.exe --operatingSystem=windows
    
    dir