language: cpp

branches:
  only:
    - master

compiler: gcc

# upgrade packages
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y python3; fi
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX
  - which $CXX_COMPILER

# install mpi
install:
  - bash ci/travis/installMPI 

before_script:
  - mkdir build
  - cd build

# build instructions
script:
  - cmake -G "Unix Makefiles" ../
  - cd $TRAVIS_BUILD_DIR/build
  - make -j 4
  - sudo make install
  - cd ../testcases
  - ls
  - python3 regressionTests.py --mpirunPath=mpirun --exePath=Test --operatingSystem=$TRAVIS_OS_NAME
